name: Deploy python application and react

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /www/wwwroot/F5/
    steps:
    - uses: actions/checkout@v4

    - name: Copy source
      run: cp -r /home/f5/actions-runner/_work/F5/F5/* /www/wwwroot/F5/

    - name: Set up Python version
      uses: actions/setup-python@v3
      with:
        python-version: "${{ env.PYTHON_VERSION || '3.x' }}"
        cache: 'pip'

    - name: Remove existing venv folder if it exists
      run: |
        if [ -d "/www/wwwroot/F5/backend/venv" ]; then
          rm -rf /www/wwwroot/F5/backend/venv
        fi
    - name: Create virtual environment
      run: |
        cd /www/wwwroot/F5/backend/
        python3 -m venv venv
    - name: Manually install pip in virtual environment
      run: |
        cd /www/wwwroot/F5/backend/
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        ./venv/bin/python3 get-pip.py
    - name: Verify Python and Pip versions in Virtual Environment
      run: |
        source /www/wwwroot/F5/backend/venv/bin/activate
        python3 --version
        pip --version
    - name: Install dependencies Backend
      run: |
        source /www/wwwroot/F5/backend/venv/bin/activate
        pip install -r /www/wwwroot/F5/backend/requirements.txt
    # Uncomment the following steps if frontend dependencies and build are needed
    - name: Reload Service
      run: sudo systemctl daemon-reload
    - name: restart Service
      run: sudo systemctl restart run.service
    - name: Check Service
      run: sudo systemctl status run.service
    - name: Install dependencies Frontend
      run: cd /www/wwwroot/F5/FE && npm install
    - name: Build Frontend
      run: cd /www/wwwroot/F5/FE && npm run build
